node{
  stage('SCM Checkout'){
      git 'https://github.com/tapanjella/SampleMvn' 
  }
  stage('Compile-Package'){
      def mvnHome = tool name: '3.5.4', type: 'maven'
    sh "${mnvHome}/bin/mvn -f simple_java/pom.xml package"
     
  }
}
